global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway_api'
    static_configs:
      - targets: ['gateway_api:8000']

  - job_name: 'traffic_service'
    static_configs:
      - targets: ['traffic_service:8000']

  - job_name: 'energy_service'
    static_configs:
      - targets: ['energy_service:8000']

  - job_name: 'water_service'
    static_configs:
      - targets: ['water_service:8000']

  - job_name: 'waste_service'
    static_configs:
      - targets: ['waste_service:8000']

  - job_name: 'security_service'
    static_configs:
      - targets: ['security_service:8000']
      
  - job_name: 'health_service'
    static_configs:
      - targets: ['health_service:8000']